/**
 * ChatFluent - Base de Dados de Idiomas
 * Centraliza as informações de tradução e caminhos para a UI
 */

const idiomasSuportados = [
    { id: 'pt', nome: 'Português', nativo: 'Português', flag: 'br' },
    { id: 'en', nome: 'Inglês', nativo: 'English', flag: 'us' },
    { id: 'es', nome: 'Espanhol', nativo: 'Español', flag: 'es' },
    { id: 'fr', nome: 'Francês', nativo: 'Français', flag: 'fr' },
    { id: 'it', nome: 'Italiano', nativo: 'Italiano', flag: 'it' },
    { id: 'de', nome: 'Alemão', nativo: 'Deutsch', flag: 'de' },
    { id: 'nl', nome: 'Holandês', nativo: 'Nederlands', flag: 'nl' },
    { id: 'pl', nome: 'Polonês', nativo: 'Polski', flag: 'pl' },
    { id: 'ru', nome: 'Russo', nativo: 'Русский', flag: 'ru' },
    { id: 'tr', nome: 'Turco', nativo: 'Türkçe', flag: 'tr' },
    { id: 'ja', nome: 'Japonês', nativo: '日本語', flag: 'jp' }
];

const uiTranslations = {
    pt: { 
        perfect: "Perfeito!", 
        goodRecovery: "Boa recuperação!", 
        tooManyErrors: "Muitos erros. Avançando...", 
        incorrect: "Incorreto. Dica:",
        excellent: "Excelente!",
        notThisTime: "Não foi dessa vez!",
        failTryAgain: "Tente novamente",
        successMastered: "MASTERED! 🏆",
        successLevelUp: "LEVEL UP! 🔓",
        restartJourney: "Reiniciar Jornada",
        tryAgain: "Tentar Novamente",
        nextLevel: "Próximo Nível",
        performance: "Aproveitamento:",
        metaAdvance: "(Meta para avançar: 80%)",
        totalScore: "Pontuação Total:",
        share: "Compartilhe"
    },
    en: { 
        perfect: "Perfect!", 
        goodRecovery: "Good recovery!", 
        tooManyErrors: "Too many errors. Moving on...", 
        incorrect: "Incorrect. Tip:",
        excellent: "Excellent!",
        notThisTime: "Better luck next time!",
        failTryAgain: "Try again",
        successMastered: "MASTERED! 🏆",
        successLevelUp: "LEVEL UP! 🔓",
        restartJourney: "Restart Journey",
        tryAgain: "Try Again",
        nextLevel: "Next Level",
        performance: "Performance:",
        metaAdvance: "(Goal to advance: 80%)",
        totalScore: "Total Score:",
        share: "Share"
    },
    es: { 
        perfect: "¡Perfecto!", 
        goodRecovery: "¡Buena recuperación!", 
        tooManyErrors: "Demasiados errores. Avanzando...", 
        incorrect: "Incorrecto. Consejo:",
        excellent: "¡Excelente!",
        notThisTime: "¡No ha sido esta vez!",
        failTryAgain: "Inténtalo de nuevo",
        successMastered: "¡DOMINADO! 🏆",
        successLevelUp: "¡SUBIDA DE NIVEL! 🔓",
        restartJourney: "Reiniciar Jornada",
        tryAgain: "Intentar de Nuevo",
        nextLevel: "Siguiente Nivel",
        performance: "Aprovechamiento:",
        metaAdvance: "(Meta para avanzar: 80%)",
        totalScore: "Puntuación Total:",
        share: "Compartir"
    },
    fr: { 
        perfect: "Parfait !", 
        goodRecovery: "Bonne récupération !", 
        tooManyErrors: "Trop d'erreurs. On avance...", 
        incorrect: "Incorrect. Astuce:",
        excellent: "Excellent !",
        notThisTime: "Ce n'est pas pour cette fois !",
        failTryAgain: "Réessayez",
        successMastered: "MAÎTRISÉ ! 🏆",
        successLevelUp: "NIVEAU SUPÉRIEUR ! 🔓",
        restartJourney: "Recommencer le voyage",
        tryAgain: "Réessayer",
        nextLevel: "Niveau suivant",
        performance: "Performance :",
        metaAdvance: "(Objectif pour avancer : 80 %)",
        totalScore: "Score total :",
        share: "Partager"
    },
    it: { 
        perfect: "Perfetto!", 
        goodRecovery: "Buon recupero!", 
        tooManyErrors: "Troppi errori. Andiamo avanti...", 
        incorrect: "Sbagliato. Suggerimento:",
        excellent: "Eccellente!",
        notThisTime: "Non è andata bene questa volta!",
        failTryAgain: "Riprova",
        successMastered: "COMPLETATO! 🏆",
        successLevelUp: "LIVELLO SUPERATO! 🔓",
        restartJourney: "Ricomincia il Viaggio",
        tryAgain: "Riprova",
        nextLevel: "Prossimo Livello",
        performance: "Rendimento:",
        metaAdvance: "(Obiettivo per avanzare: 80%)",
        totalScore: "Punteggio Totale:",
        share: "Condividi"
    },
    de: { 
        perfect: "Perfekt!", 
        goodRecovery: "Gute Erholung!", 
        tooManyErrors: "Zu viele Fehler. Weiter geht's...", 
        incorrect: "Falsch. Tipp:",
        excellent: "Hervorragend!",
        notThisTime: "Nicht dieses Mal!",
        failTryAgain: "Versuche es noch einmal",
        successMastered: "MEISTERHAFT! 🏆",
        successLevelUp: "LEVEL UP! 🔓",
        restartJourney: "Reise neu starten",
        tryAgain: "Nochmal versuchen",
        nextLevel: "Nächstes Level",
        performance: "Erfolgsquote:",
        metaAdvance: "(Ziel zum Vorankommen: 80%)",
        totalScore: "Gesamtpunktzahl:",
        share: "Teilen"
    },
    nl: { 
        perfect: "Perfect!", 
        goodRecovery: "Goed hersteld!", 
        tooManyErrors: "Te veel fouten. We gaan door...", 
        incorrect: "Fout. Tip:",
        excellent: "Uitstekend!",
        notThisTime: "Niet deze keer!",
        failTryAgain: "Probeer het opnieuw",
        successMastered: "BEHEERST! 🏆",
        successLevelUp: "LEVEL UP! 🔓",
        restartJourney: "Reis opnieuw starten",
        tryAgain: "Opnieuw Proberen",
        nextLevel: "Volgend Niveau",
        performance: "Prestatie:",
        metaAdvance: "(Doel om verder te gaan: 80%)",
        totalScore: "Totale Score:",
        share: "Delen"
    },
    pl: { 
        perfect: "Idealnie!", 
        goodRecovery: "Dobra poprawa!", 
        tooManyErrors: "Zbyt wiele błędów. Idziemy dalej...", 
        incorrect: "Niepoprawnie. Wskazówka:",
        excellent: "Doskonale!",
        notThisTime: "Nie tym razem!",
        failTryAgain: "Spróbuj ponownie",
        successMastered: "OPANOWANE! 🏆",
        successLevelUp: "AWANS! 🔓",
        restartJourney: "Zacznij podróż od nowa",
        tryAgain: "Spróbuj Ponownie",
        nextLevel: "Następny Poziom",
        performance: "Wynik:",
        metaAdvance: "(Cel, aby awansować: 80%)",
        totalScore: "Wynik Całkowity:",
        share: "Udostępnij"
    },
    ru: { 
        perfect: "Отлично!", 
        goodRecovery: "Хорошее исправление!", 
        tooManyErrors: "Слишком много ошибок. Идем дальше...", 
        incorrect: "Неверно. Подсказка:",
        excellent: "Отлично!",
        notThisTime: "Не в этот раз!",
        failTryAgain: "Попробуйте еще раз",
        successMastered: "ОСВОЕНО! 🏆",
        successLevelUp: "НОВЫЙ УРОВЕНЬ! 🔓",
        restartJourney: "Начать путешествие заново",
        tryAgain: "Попробовать Еще Раз",
        nextLevel: "Следующий Уровень",
        performance: "Успеваемость:",
        metaAdvance: "(Цель для продвижения: 80%)",
        totalScore: "Всего очков:",
        share: "Поделиться"
    },
    tr: { 
        perfect: "Harika!", 
        goodRecovery: "İyi toparladın!", 
        tooManyErrors: "Çok fazla hata. Devam ediliyor...", 
        incorrect: "Yanlış. İpucu:",
        excellent: "Mükemmel!",
        notThisTime: "Bu sefer olmadı!",
        failTryAgain: "Tekrar deneyin",
        successMastered: "UZMANLAŞILDI! 🏆",
        successLevelUp: "SEVİYE ATLAMA! 🔓",
        restartJourney: "Yolculuğu Yeniden Başlat",
        tryAgain: "Tekrar Dene",
        nextLevel: "Sonraki Seviye",
        performance: "Başarı Oranı:",
        metaAdvance: "(İlerleme hedefi: %80)",
        totalScore: "Toplam Puan:",
        share: "Paylaş"
    },
    ja: { 
        perfect: "完璧です！", 
        goodRecovery: "よく挽回しました！", 
        tooManyErrors: "エラーが多すぎます。次に進みます...", 
        incorrect: "不正解です。ヒント：",
        excellent: "素晴らしい！",
        notThisTime: "今回は残念でした！",
        failTryAgain: "もう一度挑戦してください",
        successMastered: "マスターしました！🏆",
        successLevelUp: "レベルアップ！🔓",
        restartJourney: "ジャーニーを再開する",
        tryAgain: "もう一度試す",
        nextLevel: "次のレベル",
        performance: "達成率：",
        metaAdvance: "(進級目標：80%)",
        totalScore: "合計スコア：",
        share: "シェアする"
    }
};

if (typeof module !== 'undefined') {
    module.exports = { idiomasSuportados, uiTranslations };
}