// All story scenarios for ChatFluent
// Each story has steps with NPC dialogue, options, and multilingual explanations

export const LANGUAGES = [
  { code: 'pt', name: 'Português', flag: '🇧🇷' },
  { code: 'en', name: 'English', flag: '🇺🇸' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'pl', name: 'Polski', flag: '🇵🇱' },
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'it', name: 'Italiano', flag: '🇮🇹' },
  { code: 'nl', name: 'Nederlands', flag: '🇳🇱' },
  { code: 'ru', name: 'Русский', flag: '🇷🇺' },
  { code: 'tr', name: 'Türkçe', flag: '🇹🇷' },
  { code: 'ja', name: '日本語', flag: '🇯🇵' },
];

export const FEEDBACK = {
  correct: {
    pt: '✅ Muito bem! Resposta correta!',
    en: '✅ Great job! Correct answer!',
    de: '✅ Sehr gut! Richtige Antwort!',
    pl: '✅ Świetnie! Poprawna odpowiedź!',
    es: '✅ ¡Muy bien! ¡Respuesta correcta!',
    fr: '✅ Très bien ! Bonne réponse !',
    it: '✅ Molto bene! Risposta corretta!',
    nl: '✅ Heel goed! Juist antwoord!',
    ru: '✅ Отлично! Правильный ответ!',
    tr: '✅ Çok iyi! Doğru cevap!',
    ja: '✅ よくできました！正解です！',
  },
  incorrect: {
    pt: '❌ Quase! Tente novamente.',
    en: '❌ Almost! Try again.',
    de: '❌ Fast! Versuche es nochmal.',
    pl: '❌ Prawie! Spróbuj ponownie.',
    es: '❌ ¡Casi! Intenta otra vez.',
    fr: '❌ Presque ! Essayez encore.',
    it: '❌ Quasi! Riprova.',
    nl: '❌ Bijna! Probeer opnieuw.',
    ru: '❌ Почти! Попробуйте снова.',
    tr: '❌ Neredeyse! Tekrar dene.',
    ja: '❌ 惜しい！もう一度やってみてください。',
  },
};

export const UI_TEXTS = {
  selectLanguage: {
    pt: 'Selecione seu idioma',
    en: 'Select your language',
    de: 'Wähle deine Sprache',
    pl: 'Wybierz swój język',
    es: 'Selecciona tu idioma',
    fr: 'Choisissez votre langue',
    it: 'Seleziona la tua lingua',
    nl: 'Kies je taal',
    ru: 'Выберите свой язык',
    tr: 'Dilinizi seçin',
    ja: '言語を選択してください',
  },
  startLearning: {
    pt: 'Começar a aprender',
    en: 'Start learning',
    de: 'Lernen beginnen',
    pl: 'Zacznij się uczyć',
    es: 'Empezar a aprender',
    fr: 'Commencer à apprendre',
    it: 'Inizia a imparare',
    nl: 'Begin met leren',
    ru: 'Начать учиться',
    tr: 'Öğrenmeye başla',
    ja: '学習を始める',
  },
  score: {
    pt: 'Pontuação',
    en: 'Score',
    de: 'Punktzahl',
    pl: 'Wynik',
    es: 'Puntuación',
    fr: 'Score',
    it: 'Punteggio',
    nl: 'Score',
    ru: 'Счёт',
    tr: 'Puan',
    ja: 'スコア',
  },
  streak: {
    pt: 'Sequência',
    en: 'Streak',
    de: 'Serie',
    pl: 'Seria',
    es: 'Racha',
    fr: 'Série',
    it: 'Serie',
    nl: 'Reeks',
    ru: 'Серия',
    tr: 'Seri',
    ja: '連続',
  },
  step: {
    pt: 'Etapa',
    en: 'Step',
    de: 'Schritt',
    pl: 'Krok',
    es: 'Paso',
    fr: 'Étape',
    it: 'Passo',
    nl: 'Stap',
    ru: 'Шаг',
    tr: 'Adım',
    ja: 'ステップ',
  },
  continue: {
    pt: 'Continuar',
    en: 'Continue',
    de: 'Weiter',
    pl: 'Kontynuuj',
    es: 'Continuar',
    fr: 'Continuer',
    it: 'Continua',
    nl: 'Doorgaan',
    ru: 'Продолжить',
    tr: 'Devam',
    ja: '続ける',
  },
  tryAgain: {
    pt: 'Tentar novamente',
    en: 'Try again',
    de: 'Nochmal versuchen',
    pl: 'Spróbuj ponownie',
    es: 'Intentar de nuevo',
    fr: 'Réessayer',
    it: 'Riprova',
    nl: 'Probeer opnieuw',
    ru: 'Попробовать снова',
    tr: 'Tekrar dene',
    ja: 'もう一度',
  },
  congrats: {
    pt: '🎉 Parabéns! Você completou a história!',
    en: '🎉 Congratulations! You completed the story!',
    de: '🎉 Herzlichen Glückwunsch! Du hast die Geschichte abgeschlossen!',
    pl: '🎉 Gratulacje! Ukończyłeś historię!',
    es: '🎉 ¡Felicidades! ¡Completaste la historia!',
    fr: '🎉 Félicitations ! Vous avez terminé l\'histoire !',
    it: '🎉 Congratulazioni! Hai completato la storia!',
    nl: '🎉 Gefeliciteerd! Je hebt het verhaal voltooid!',
    ru: '🎉 Поздравляем! Вы завершили историю!',
    tr: '🎉 Tebrikler! Hikayeyi tamamladın!',
    ja: '🎉 おめでとうございます！ストーリーを完了しました！',
  },
  tooManyErrors: {
    pt: '⚠️ Muitos erros! Tente novamente para melhorar.',
    en: '⚠️ Too many errors! Try again to improve.',
    de: '⚠️ Zu viele Fehler! Versuche es erneut.',
    pl: '⚠️ Za dużo błędów! Spróbuj ponownie.',
    es: '⚠️ ¡Demasiados errores! Intenta de nuevo.',
    fr: '⚠️ Trop d\'erreurs ! Réessayez pour vous améliorer.',
    it: '⚠️ Troppi errori! Riprova per migliorare.',
    nl: '⚠️ Te veel fouten! Probeer opnieuw.',
    ru: '⚠️ Слишком много ошибок! Попробуйте снова.',
    tr: '⚠️ Çok fazla hata! Geliştirmek için tekrar dene.',
    ja: '⚠️ エラーが多すぎます！改善するためにもう一度やってみてください。',
  },
  backToStories: {
    pt: 'Voltar às histórias',
    en: 'Back to stories',
    de: 'Zurück zu den Geschichten',
    pl: 'Powrót do historii',
    es: 'Volver a las historias',
    fr: 'Retour aux histoires',
    it: 'Torna alle storie',
    nl: 'Terug naar verhalen',
    ru: 'Назад к историям',
    tr: 'Hikayelere dön',
    ja: 'ストーリーに戻る',
  },
  chooseStory: {
    pt: 'Escolha uma história',
    en: 'Choose a story',
    de: 'Wähle eine Geschichte',
    pl: 'Wybierz historię',
    es: 'Elige una historia',
    fr: 'Choisissez une histoire',
    it: 'Scegli una storia',
    nl: 'Kies een verhaal',
    ru: 'Выберите историю',
    tr: 'Bir hikaye seç',
    ja: 'ストーリーを選んでください',
  },
  level: {
    pt: 'Nível',
    en: 'Level',
    de: 'Level',
    pl: 'Poziom',
    es: 'Nivel',
    fr: 'Niveau',
    it: 'Livello',
    nl: 'Niveau',
    ru: 'Уровень',
    tr: 'Seviye',
    ja: 'レベル',
  },
};

export const STORIES = [
  {
    id: 'airport',
    icon: '✈️',
    title: {
      pt: 'No Aeroporto', en: 'At the Airport', de: 'Am Flughafen', pl: 'Na lotnisku',
      es: 'En el Aeropuerto', fr: 'À l\'Aéroport', it: 'All\'Aeroporto', nl: 'Op de Luchthaven',
      ru: 'В аэропорту', tr: 'Havalimanında', ja: '空港で',
    },
    description: {
      pt: 'Você está viajando para os EUA. Aprenda a se comunicar no aeroporto.',
      en: 'You are traveling to the USA. Learn to communicate at the airport.',
      de: 'Du reist in die USA. Lerne, am Flughafen zu kommunizieren.',
      pl: 'Podróżujesz do USA. Naucz się komunikować na lotnisku.',
      es: 'Estás viajando a los EE. UU. Aprende a comunicarte en el aeropuerto.',
      fr: 'Vous voyagez aux États-Unis. Apprenez à communiquer à l\'aéroport.',
      it: 'Stai viaggiando negli USA. Impara a comunicare in aeroporto.',
      nl: 'Je reist naar de VS. Leer communiceren op de luchthaven.',
      ru: 'Вы путешествуете в США. Научитесь общаться в аэропорту.',
      tr: 'ABD\'ye seyahat ediyorsun. Havalimanında iletişim kurmayı öğren.',
      ja: 'アメリカに旅行しています。空港でのコミュニケーションを学びましょう。',
    },
    difficulty: 'beginner',
    steps: [
      {
        npc: "Hello! Welcome to the check-in counter. Can I see your passport, please?",
        options: [
          "Yes, here is my passport.",
          "No, I don't have one.",
          "What is a passport?",
        ],
        correct: 0,
        explanation: {
          pt: '"Here is my passport" é a forma natural de entregar algo a alguém.',
          en: '"Here is my passport" is the natural way to hand something to someone.',
          de: '"Here is my passport" ist die natürliche Art, jemandem etwas zu geben.',
          pl: '"Here is my passport" to naturalny sposób wręczenia czegoś komuś.',
          es: '"Here is my passport" es la forma natural de entregar algo a alguien.',
          fr: '"Here is my passport" est la manière naturelle de remettre quelque chose.',
          it: '"Here is my passport" è il modo naturale di consegnare qualcosa.',
          nl: '"Here is my passport" is de natuurlijke manier om iets te overhandigen.',
          ru: '"Here is my passport" — естественный способ передать что-то.',
          tr: '"Here is my passport" bir şeyi teslim etmenin doğal yoludur.',
          ja: '"Here is my passport" は何かを渡す自然な表現です。',
        },
      },
      {
        npc: "Are you traveling alone or with someone?",
        options: [
          "I'm traveling alone.",
          "I travel the alone.",
          "Me traveling solo.",
        ],
        correct: 0,
        explanation: {
          pt: '"I\'m traveling alone" usa o presente contínuo corretamente.',
          en: '"I\'m traveling alone" correctly uses the present continuous.',
          de: '"I\'m traveling alone" verwendet korrekt das Present Continuous.',
          pl: '"I\'m traveling alone" poprawnie używa czasu Present Continuous.',
          es: '"I\'m traveling alone" usa correctamente el presente continuo.',
          fr: '"I\'m traveling alone" utilise correctement le présent continu.',
          it: '"I\'m traveling alone" usa correttamente il presente continuo.',
          nl: '"I\'m traveling alone" gebruikt correct de tegenwoordige tijd.',
          ru: '"I\'m traveling alone" правильно использует настоящее продолженное время.',
          tr: '"I\'m traveling alone" şimdiki zamanı doğru kullanır.',
          ja: '"I\'m traveling alone" は現在進行形を正しく使っています。',
        },
      },
      {
        npc: "How many bags are you checking in today?",
        options: [
          "I have two bags to check in.",
          "Two bags checking.",
          "Bags two please.",
        ],
        correct: 0,
        explanation: {
          pt: '"I have two bags to check in" é uma frase completa e natural.',
          en: '"I have two bags to check in" is a complete and natural sentence.',
          de: '"I have two bags to check in" ist ein vollständiger Satz.',
          pl: '"I have two bags to check in" to pełne i naturalne zdanie.',
          es: '"I have two bags to check in" es una oración completa y natural.',
          fr: '"I have two bags to check in" est une phrase complète et naturelle.',
          it: '"I have two bags to check in" è una frase completa e naturale.',
          nl: '"I have two bags to check in" is een volledige en natuurlijke zin.',
          ru: '"I have two bags to check in" — полное и естественное предложение.',
          tr: '"I have two bags to check in" eksiksiz ve doğal bir cümledir.',
          ja: '"I have two bags to check in" は完全で自然な文です。',
        },
      },
      {
        npc: "Would you like a window seat or an aisle seat?",
        options: [
          "A window seat, please.",
          "I want the window.",
          "Window me please.",
        ],
        correct: 0,
        explanation: {
          pt: '"A window seat, please" é educado e direto.',
          en: '"A window seat, please" is polite and direct.',
          de: '"A window seat, please" ist höflich und direkt.',
          pl: '"A window seat, please" jest uprzejme i bezpośrednie.',
          es: '"A window seat, please" es educado y directo.',
          fr: '"A window seat, please" est poli et direct.',
          it: '"A window seat, please" è educato e diretto.',
          nl: '"A window seat, please" is beleefd en direct.',
          ru: '"A window seat, please" — вежливо и прямо.',
          tr: '"A window seat, please" kibar ve doğrudandır.',
          ja: '"A window seat, please" は丁寧で直接的な表現です。',
        },
      },
      {
        npc: "Your flight is at Gate B12. It boards in 45 minutes. Do you have any questions?",
        options: [
          "Where can I find Gate B12?",
          "What is gate?",
          "B12 where is go?",
        ],
        correct: 0,
        explanation: {
          pt: '"Where can I find...?" é a forma correta de perguntar por um local.',
          en: '"Where can I find...?" is the correct way to ask for a location.',
          de: '"Where can I find...?" ist die richtige Art, nach einem Ort zu fragen.',
          pl: '"Where can I find...?" to poprawny sposób pytania o lokalizację.',
          es: '"Where can I find...?" es la forma correcta de preguntar por un lugar.',
          fr: '"Where can I find...?" est la bonne façon de demander un endroit.',
          it: '"Where can I find...?" è il modo corretto per chiedere un luogo.',
          nl: '"Where can I find...?" is de juiste manier om naar een locatie te vragen.',
          ru: '"Where can I find...?" — правильный способ спросить о местоположении.',
          tr: '"Where can I find...?" bir yer sormak için doğru ifadedir.',
          ja: '"Where can I find...?" は場所を尋ねる正しい方法です。',
        },
      },
      {
        npc: "Go straight and turn right after the duty-free shop. You can't miss it.",
        options: [
          "Thank you very much!",
          "Thanks you very!",
          "Good thank.",
        ],
        correct: 0,
        explanation: {
          pt: '"Thank you very much" é a forma padrão de agradecer.',
          en: '"Thank you very much" is the standard way to express gratitude.',
          de: '"Thank you very much" ist die Standardform, um sich zu bedanken.',
          pl: '"Thank you very much" to standardowy sposób wyrażenia wdzięczności.',
          es: '"Thank you very much" es la forma estándar de expresar gratitud.',
          fr: '"Thank you very much" est la manière standard d\'exprimer sa gratitude.',
          it: '"Thank you very much" è il modo standard per esprimere gratitudine.',
          nl: '"Thank you very much" is de standaardmanier om dankbaarheid uit te drukken.',
          ru: '"Thank you very much" — стандартный способ выразить благодарность.',
          tr: '"Thank you very much" minnettarlığı ifade etmenin standart yoludur.',
          ja: '"Thank you very much" は感謝を表す標準的な表現です。',
        },
      },
      {
        npc: "Excuse me, this is a security check. Please remove your belt and shoes.",
        options: [
          "Sure, no problem.",
          "Why I remove?",
          "No, I keep.",
        ],
        correct: 0,
        explanation: {
          pt: '"Sure, no problem" mostra cooperação de forma natural.',
          en: '"Sure, no problem" shows cooperation naturally.',
          de: '"Sure, no problem" zeigt Kooperationsbereitschaft.',
          pl: '"Sure, no problem" naturalnie wyraża współpracę.',
          es: '"Sure, no problem" muestra cooperación de manera natural.',
          fr: '"Sure, no problem" montre la coopération naturellement.',
          it: '"Sure, no problem" mostra cooperazione in modo naturale.',
          nl: '"Sure, no problem" toont medewerking op een natuurlijke manier.',
          ru: '"Sure, no problem" — естественное выражение готовности помочь.',
          tr: '"Sure, no problem" doğal bir şekilde iş birliği gösterir.',
          ja: '"Sure, no problem" は自然に協力を示す表現です。',
        },
      },
      {
        npc: "Do you have any liquids in your carry-on bag?",
        options: [
          "Yes, I have a small bottle of water.",
          "Liquid yes bag have.",
          "I having the liquids.",
        ],
        correct: 0,
        explanation: {
          pt: 'Resposta completa com "I have" é o correto em inglês.',
          en: 'A complete answer with "I have" is correct English.',
          de: 'Eine vollständige Antwort mit "I have" ist korrektes Englisch.',
          pl: 'Pełna odpowiedź z "I have" to poprawny angielski.',
          es: 'Una respuesta completa con "I have" es inglés correcto.',
          fr: 'Une réponse complète avec "I have" est du bon anglais.',
          it: 'Una risposta completa con "I have" è inglese corretto.',
          nl: 'Een volledig antwoord met "I have" is correct Engels.',
          ru: 'Полный ответ с "I have" — правильный английский.',
          tr: '"I have" ile tam bir cevap doğru İngilizcedir.',
          ja: '"I have" を使った完全な文が正しい英語です。',
        },
      },
      {
        npc: "Now boarding: Flight AA215 to New York. Please have your boarding pass ready.",
        options: [
          "Here's my boarding pass.",
          "I have not the pass of board.",
          "Pass board here.",
        ],
        correct: 0,
        explanation: {
          pt: '"Here\'s my boarding pass" é direto e educado.',
          en: '"Here\'s my boarding pass" is direct and polite.',
          de: '"Here\'s my boarding pass" ist direkt und höflich.',
          pl: '"Here\'s my boarding pass" jest bezpośrednie i uprzejme.',
          es: '"Here\'s my boarding pass" es directo y educado.',
          fr: '"Here\'s my boarding pass" est direct et poli.',
          it: '"Here\'s my boarding pass" è diretto e educato.',
          nl: '"Here\'s my boarding pass" is direct en beleefd.',
          ru: '"Here\'s my boarding pass" — прямо и вежливо.',
          tr: '"Here\'s my boarding pass" doğrudan ve kibardır.',
          ja: '"Here\'s my boarding pass" は直接的で丁寧な表現です。',
        },
      },
      {
        npc: "Welcome aboard! Your seat is 14A. Enjoy your flight!",
        options: [
          "Thank you! Have a nice day!",
          "Yes flight enjoy.",
          "OK seat go.",
        ],
        correct: 0,
        explanation: {
          pt: '"Thank you! Have a nice day!" é cordial e natural.',
          en: '"Thank you! Have a nice day!" is friendly and natural.',
          de: '"Thank you! Have a nice day!" ist freundlich und natürlich.',
          pl: '"Thank you! Have a nice day!" jest przyjazne i naturalne.',
          es: '"Thank you! Have a nice day!" es amable y natural.',
          fr: '"Thank you! Have a nice day!" est amical et naturel.',
          it: '"Thank you! Have a nice day!" è cordiale e naturale.',
          nl: '"Thank you! Have a nice day!" is vriendelijk en natuurlijk.',
          ru: '"Thank you! Have a nice day!" — дружелюбно и естественно.',
          tr: '"Thank you! Have a nice day!" samimi ve doğaldır.',
          ja: '"Thank you! Have a nice day!" はフレンドリーで自然な表現です。',
        },
      },
    ],
  },
  {
    id: 'restaurant',
    icon: '🍽️',
    title: {
      pt: 'No Restaurante', en: 'At the Restaurant', de: 'Im Restaurant', pl: 'W restauracji',
      es: 'En el Restaurante', fr: 'Au Restaurant', it: 'Al Ristorante', nl: 'In het Restaurant',
      ru: 'В ресторане', tr: 'Restoranda', ja: 'レストランで',
    },
    description: {
      pt: 'Peça comida, converse com o garçom e pague a conta em inglês.',
      en: 'Order food, talk to the waiter and pay the bill in English.',
      de: 'Bestelle Essen, sprich mit dem Kellner und bezahle auf Englisch.',
      pl: 'Zamów jedzenie, porozmawiaj z kelnerem i zapłać rachunek po angielsku.',
      es: 'Pide comida, habla con el mesero y paga la cuenta en inglés.',
      fr: 'Commandez, parlez au serveur et payez l\'addition en anglais.',
      it: 'Ordina cibo, parla con il cameriere e paga il conto in inglese.',
      nl: 'Bestel eten, praat met de ober en betaal de rekening in het Engels.',
      ru: 'Закажите еду, поговорите с официантом и оплатите счёт по-английски.',
      tr: 'Yemek sipariş et, garsonla konuş ve hesabı İngilizce öde.',
      ja: '食事を注文し、ウェイターと話し、英語で会計しましょう。',
    },
    difficulty: 'beginner',
    steps: [
      {
        npc: "Good evening! Welcome to The Golden Fork. Do you have a reservation?",
        options: [
          "Yes, I have a reservation for two under the name Smith.",
          "Reservation I have two.",
          "Table want now.",
        ],
        correct: 0,
        explanation: {
          pt: '"I have a reservation for two under the name..." é como você faz reserva em restaurantes.',
          en: '"I have a reservation for two under the name..." is how you confirm a restaurant reservation.',
          de: '"I have a reservation for two under the name..." so bestätigt man eine Reservierung.',
          pl: '"I have a reservation for two under the name..." tak potwierdzasz rezerwację.',
          es: '"I have a reservation for two under the name..." así confirmas una reserva.',
          fr: '"I have a reservation for two under the name..." c\'est comme ça qu\'on confirme.',
          it: '"I have a reservation for two under the name..." è come si conferma una prenotazione.',
          nl: '"I have a reservation for two under the name..." zo bevestig je een reservering.',
          ru: '"I have a reservation for two under the name..." — так подтверждают бронирование.',
          tr: '"I have a reservation for two under the name..." rezervasyonu böyle onaylarsınız.',
          ja: '"I have a reservation for two under the name..." はレストランの予約を確認する方法です。',
        },
      },
      {
        npc: "Here's your table. Can I get you something to drink?",
        options: [
          "I'd like a glass of water, please.",
          "Water me give.",
          "Drink want I.",
        ],
        correct: 0,
        explanation: {
          pt: '"I\'d like..." é a forma educada de pedir algo.',
          en: '"I\'d like..." is the polite way to request something.',
          de: '"I\'d like..." ist die höfliche Art, etwas zu bestellen.',
          pl: '"I\'d like..." to uprzejmy sposób na zamówienie czegoś.',
          es: '"I\'d like..." es la forma educada de pedir algo.',
          fr: '"I\'d like..." est la manière polie de demander quelque chose.',
          it: '"I\'d like..." è il modo educato per ordinare qualcosa.',
          nl: '"I\'d like..." is de beleefde manier om iets te bestellen.',
          ru: '"I\'d like..." — вежливый способ что-то попросить.',
          tr: '"I\'d like..." bir şey istemenin kibar yoludur.',
          ja: '"I\'d like..." は何かを頼む丁寧な表現です。',
        },
      },
      {
        npc: "Are you ready to order, or do you need a few more minutes?",
        options: [
          "I need a few more minutes, please.",
          "Minutes more I need.",
          "Not ready. Wait.",
        ],
        correct: 0,
        explanation: {
          pt: '"I need a few more minutes" é educado e completo.',
          en: '"I need a few more minutes" is polite and complete.',
          de: '"I need a few more minutes" ist höflich und vollständig.',
          pl: '"I need a few more minutes" jest uprzejme i kompletne.',
          es: '"I need a few more minutes" es educado y completo.',
          fr: '"I need a few more minutes" est poli et complet.',
          it: '"I need a few more minutes" è educato e completo.',
          nl: '"I need a few more minutes" is beleefd en volledig.',
          ru: '"I need a few more minutes" — вежливо и полно.',
          tr: '"I need a few more minutes" kibar ve eksiksizdir.',
          ja: '"I need a few more minutes" は丁寧で完全な表現です。',
        },
      },
      {
        npc: "What would you like to have for your main course?",
        options: [
          "I'll have the grilled chicken with vegetables, please.",
          "Chicken grill vegetable.",
          "Give me the food chicken.",
        ],
        correct: 0,
        explanation: {
          pt: '"I\'ll have..." é a forma padrão de fazer um pedido.',
          en: '"I\'ll have..." is the standard way to place an order.',
          de: '"I\'ll have..." ist die Standardform, um zu bestellen.',
          pl: '"I\'ll have..." to standardowy sposób składania zamówienia.',
          es: '"I\'ll have..." es la forma estándar de hacer un pedido.',
          fr: '"I\'ll have..." est la façon standard de passer commande.',
          it: '"I\'ll have..." è il modo standard per ordinare.',
          nl: '"I\'ll have..." is de standaardmanier om te bestellen.',
          ru: '"I\'ll have..." — стандартный способ сделать заказ.',
          tr: '"I\'ll have..." sipariş vermenin standart yoludur.',
          ja: '"I\'ll have..." は注文する標準的な方法です。',
        },
      },
      {
        npc: "How would you like your steak cooked?",
        options: [
          "Medium rare, please.",
          "Cook it the middle.",
          "Not much fire.",
        ],
        correct: 0,
        explanation: {
          pt: '"Medium rare" é o termo correto para ponto de carne.',
          en: '"Medium rare" is the correct term for steak doneness.',
          de: '"Medium rare" ist der richtige Begriff für den Gargrad.',
          pl: '"Medium rare" to prawidłowy termin na stopień wysmażenia.',
          es: '"Medium rare" es el término correcto para el punto de cocción.',
          fr: '"Medium rare" est le terme correct pour la cuisson.',
          it: '"Medium rare" è il termine corretto per la cottura.',
          nl: '"Medium rare" is de juiste term voor de gaarheid.',
          ru: '"Medium rare" — правильный термин для прожарки.',
          tr: '"Medium rare" pişirme derecesi için doğru terimdir.',
          ja: '"Medium rare" はステーキの焼き加減を表す正しい用語です。',
        },
      },
      {
        npc: "Would you like to see the dessert menu?",
        options: [
          "Yes, please! What do you recommend?",
          "Dessert show me.",
          "Sweet food want.",
        ],
        correct: 0,
        explanation: {
          pt: '"What do you recommend?" é uma ótima pergunta para o garçom.',
          en: '"What do you recommend?" is a great question for the waiter.',
          de: '"What do you recommend?" ist eine tolle Frage an den Kellner.',
          pl: '"What do you recommend?" to świetne pytanie do kelnera.',
          es: '"What do you recommend?" es una gran pregunta para el mesero.',
          fr: '"What do you recommend?" est une excellente question pour le serveur.',
          it: '"What do you recommend?" è un\'ottima domanda per il cameriere.',
          nl: '"What do you recommend?" is een geweldige vraag voor de ober.',
          ru: '"What do you recommend?" — отличный вопрос официанту.',
          tr: '"What do you recommend?" garson için harika bir sorudur.',
          ja: '"What do you recommend?" はウェイターへの素晴らしい質問です。',
        },
      },
      {
        npc: "Can I bring you the check?",
        options: [
          "Yes, please. Can I pay by card?",
          "Check give money.",
          "Pay want now card.",
        ],
        correct: 0,
        explanation: {
          pt: '"Can I pay by card?" é a forma natural de perguntar sobre pagamento.',
          en: '"Can I pay by card?" is the natural way to ask about payment.',
          de: '"Can I pay by card?" ist die natürliche Art, nach Zahlung zu fragen.',
          pl: '"Can I pay by card?" to naturalny sposób pytania o płatność.',
          es: '"Can I pay by card?" es la forma natural de preguntar sobre el pago.',
          fr: '"Can I pay by card?" est la façon naturelle de demander le paiement.',
          it: '"Can I pay by card?" è il modo naturale per chiedere il pagamento.',
          nl: '"Can I pay by card?" is de natuurlijke manier om naar betaling te vragen.',
          ru: '"Can I pay by card?" — естественный способ спросить об оплате.',
          tr: '"Can I pay by card?" ödeme hakkında sormanın doğal yoludur.',
          ja: '"Can I pay by card?" は支払いについて尋ねる自然な方法です。',
        },
      },
      {
        npc: "Of course! Here's the card machine. The total is $45.80.",
        options: [
          "Thank you. The food was delicious!",
          "Good food bye.",
          "Delicious was it.",
        ],
        correct: 0,
        explanation: {
          pt: '"The food was delicious" é um elogio natural ao restaurante.',
          en: '"The food was delicious" is a natural compliment to the restaurant.',
          de: '"The food was delicious" ist ein natürliches Kompliment.',
          pl: '"The food was delicious" to naturalny komplement dla restauracji.',
          es: '"The food was delicious" es un cumplido natural al restaurante.',
          fr: '"The food was delicious" est un compliment naturel.',
          it: '"The food was delicious" è un complimento naturale.',
          nl: '"The food was delicious" is een natuurlijk compliment.',
          ru: '"The food was delicious" — естественный комплимент ресторану.',
          tr: '"The food was delicious" restorana doğal bir iltifattır.',
          ja: '"The food was delicious" はレストランへの自然な褒め言葉です。',
        },
      },
    ],
  },
  {
    id: 'hotel',
    icon: '🏨',
    title: {
      pt: 'No Hotel', en: 'At the Hotel', de: 'Im Hotel', pl: 'W hotelu',
      es: 'En el Hotel', fr: 'À l\'Hôtel', it: 'In Hotel', nl: 'In het Hotel',
      ru: 'В отеле', tr: 'Otelde', ja: 'ホテルで',
    },
    description: {
      pt: 'Faça check-in, peça informações e resolva problemas no hotel.',
      en: 'Check in, ask for information and solve problems at the hotel.',
      de: 'Einchecken, Informationen erfragen und Probleme im Hotel lösen.',
      pl: 'Zamelduj się, poproś o informacje i rozwiąż problemy w hotelu.',
      es: 'Regístrate, pide información y resuelve problemas en el hotel.',
      fr: 'Enregistrez-vous, demandez des infos et résolvez des problèmes.',
      it: 'Fai il check-in, chiedi informazioni e risolvi problemi in hotel.',
      nl: 'Check in, vraag informatie en los problemen op in het hotel.',
      ru: 'Заселитесь, спросите информацию и решите проблемы в отеле.',
      tr: 'Giriş yap, bilgi iste ve otelde sorunları çöz.',
      ja: 'チェックインし、情報を聞き、ホテルでの問題を解決しましょう。',
    },
    difficulty: 'beginner',
    steps: [
      {
        npc: "Good afternoon! Welcome to the Grand Hotel. Do you have a reservation?",
        options: [
          "Yes, I booked a room online. My name is Johnson.",
          "Room I want book.",
          "Reservation online yes.",
        ],
        correct: 0,
        explanation: {
          pt: '"I booked a room online" é a frase completa correta.',
          en: '"I booked a room online" is the correct complete sentence.',
          de: '"I booked a room online" ist der korrekte vollständige Satz.',
          pl: '"I booked a room online" to poprawne kompletne zdanie.',
          es: '"I booked a room online" es la oración completa correcta.',
          fr: '"I booked a room online" est la phrase complète correcte.',
          it: '"I booked a room online" è la frase completa corretta.',
          nl: '"I booked a room online" is de juiste volledige zin.',
          ru: '"I booked a room online" — правильное полное предложение.',
          tr: '"I booked a room online" doğru tam cümledir.',
          ja: '"I booked a room online" は正しい完全な文です。',
        },
      },
      {
        npc: "I found your reservation. Would you like a room with a city view or a garden view?",
        options: [
          "I'd prefer a city view, please.",
          "City window want.",
          "View the city me.",
        ],
        correct: 0,
        explanation: {
          pt: '"I\'d prefer..." é uma forma educada de expressar preferência.',
          en: '"I\'d prefer..." is a polite way to express preference.',
          de: '"I\'d prefer..." ist eine höfliche Art, Vorlieben auszudrücken.',
          pl: '"I\'d prefer..." to uprzejmy sposób wyrażenia preferencji.',
          es: '"I\'d prefer..." es una forma educada de expresar preferencia.',
          fr: '"I\'d prefer..." est une façon polie d\'exprimer une préférence.',
          it: '"I\'d prefer..." è un modo educato per esprimere una preferenza.',
          nl: '"I\'d prefer..." is een beleefde manier om voorkeur uit te drukken.',
          ru: '"I\'d prefer..." — вежливый способ выразить предпочтение.',
          tr: '"I\'d prefer..." tercih belirtmenin kibar yoludur.',
          ja: '"I\'d prefer..." は好みを表す丁寧な方法です。',
        },
      },
      {
        npc: "What time is breakfast served?",
        options: [
          "Could you tell me what time breakfast starts?",
          "Breakfast when?",
          "Food morning time?",
        ],
        correct: 0,
        explanation: {
          pt: '"Could you tell me..." é a forma educada de pedir informação.',
          en: '"Could you tell me..." is the polite way to ask for information.',
          de: '"Could you tell me..." ist die höfliche Art, nach Informationen zu fragen.',
          pl: '"Could you tell me..." to uprzejmy sposób pytania o informacje.',
          es: '"Could you tell me..." es la forma educada de pedir información.',
          fr: '"Could you tell me..." est la façon polie de demander des informations.',
          it: '"Could you tell me..." è il modo educato per chiedere informazioni.',
          nl: '"Could you tell me..." is de beleefde manier om informatie te vragen.',
          ru: '"Could you tell me..." — вежливый способ запросить информацию.',
          tr: '"Could you tell me..." bilgi istemenin kibar yoludur.',
          ja: '"Could you tell me..." は情報を求める丁寧な方法です。',
        },
      },
      {
        npc: "Breakfast is from 7 to 10 AM in the restaurant on the second floor. Is there anything else?",
        options: [
          "Yes, is there a gym in the hotel?",
          "Gym hotel have?",
          "Where sport make?",
        ],
        correct: 0,
        explanation: {
          pt: '"Is there a...?" é a forma correta de perguntar se algo existe.',
          en: '"Is there a...?" is the correct way to ask if something exists.',
          de: '"Is there a...?" ist die richtige Art zu fragen, ob etwas existiert.',
          pl: '"Is there a...?" to poprawny sposób pytania, czy coś istnieje.',
          es: '"Is there a...?" es la forma correcta de preguntar si algo existe.',
          fr: '"Is there a...?" est la bonne façon de demander si quelque chose existe.',
          it: '"Is there a...?" è il modo corretto per chiedere se qualcosa esiste.',
          nl: '"Is there a...?" is de juiste manier om te vragen of iets bestaat.',
          ru: '"Is there a...?" — правильный способ спросить о наличии чего-либо.',
          tr: '"Is there a...?" bir şeyin var olup olmadığını sormanın doğru yoludur.',
          ja: '"Is there a...?" は何かがあるかどうかを尋ねる正しい方法です。',
        },
      },
      {
        npc: "I'm sorry, the Wi-Fi in your room isn't working. We'll send someone to fix it.",
        options: [
          "Thank you. How long will it take?",
          "Wi-Fi fix when?",
          "Internet me need now.",
        ],
        correct: 0,
        explanation: {
          pt: '"How long will it take?" é a forma correta de perguntar sobre tempo.',
          en: '"How long will it take?" is the correct way to ask about time.',
          de: '"How long will it take?" ist die richtige Art, nach der Zeit zu fragen.',
          pl: '"How long will it take?" to poprawny sposób pytania o czas.',
          es: '"How long will it take?" es la forma correcta de preguntar sobre el tiempo.',
          fr: '"How long will it take?" est la bonne façon de demander combien de temps.',
          it: '"How long will it take?" è il modo corretto per chiedere il tempo.',
          nl: '"How long will it take?" is de juiste manier om naar de tijd te vragen.',
          ru: '"How long will it take?" — правильный способ спросить о времени.',
          tr: '"How long will it take?" zaman hakkında sormanın doğru yoludur.',
          ja: '"How long will it take?" は時間を尋ねる正しい方法です。',
        },
      },
      {
        npc: "It should be about 15 minutes. Is your room comfortable otherwise?",
        options: [
          "Yes, the room is very nice. Thank you for asking.",
          "Room good. Thanks ask.",
          "Comfortable yes it is room.",
        ],
        correct: 0,
        explanation: {
          pt: 'Resposta completa e educada com "Thank you for asking".',
          en: 'Complete and polite answer with "Thank you for asking".',
          de: 'Vollständige und höfliche Antwort mit "Thank you for asking".',
          pl: 'Kompletna i uprzejma odpowiedź z "Thank you for asking".',
          es: 'Respuesta completa y educada con "Thank you for asking".',
          fr: 'Réponse complète et polie avec "Thank you for asking".',
          it: 'Risposta completa e educata con "Thank you for asking".',
          nl: 'Volledig en beleefd antwoord met "Thank you for asking".',
          ru: 'Полный и вежливый ответ с "Thank you for asking".',
          tr: '"Thank you for asking" ile tam ve kibar cevap.',
          ja: '"Thank you for asking" を含む完全で丁寧な回答です。',
        },
      },
      {
        npc: "I'd like to check out now. Can I leave my bags here for a few hours?",
        options: [
          "Of course! We have a luggage storage area.",
          "Bags leave here yes.",
          "Storage bag hours.",
        ],
        correct: 0,
        explanation: {
          pt: '"Luggage storage area" é o termo correto para guarda-volumes.',
          en: '"Luggage storage area" is the correct term for bag storage.',
          de: '"Luggage storage area" ist der richtige Begriff für Gepäckaufbewahrung.',
          pl: '"Luggage storage area" to prawidłowy termin na przechowalnię bagażu.',
          es: '"Luggage storage area" es el término correcto para guardar equipaje.',
          fr: '"Luggage storage area" est le terme correct pour la consigne.',
          it: '"Luggage storage area" è il termine corretto per il deposito bagagli.',
          nl: '"Luggage storage area" is de juiste term voor bagageopslag.',
          ru: '"Luggage storage area" — правильный термин для камеры хранения.',
          tr: '"Luggage storage area" bagaj saklama için doğru terimdir.',
          ja: '"Luggage storage area" は荷物預かり所の正しい用語です。',
        },
      },
      {
        npc: "Here's your receipt. We hope you enjoyed your stay!",
        options: [
          "It was a wonderful stay. I'll definitely come back!",
          "Stay good come back.",
          "Wonderful yes return.",
        ],
        correct: 0,
        explanation: {
          pt: '"It was a wonderful stay" é um feedback positivo completo.',
          en: '"It was a wonderful stay" is a complete positive feedback.',
          de: '"It was a wonderful stay" ist ein vollständiges positives Feedback.',
          pl: '"It was a wonderful stay" to kompletna pozytywna opinia.',
          es: '"It was a wonderful stay" es un comentario positivo completo.',
          fr: '"It was a wonderful stay" est un retour positif complet.',
          it: '"It was a wonderful stay" è un feedback positivo completo.',
          nl: '"It was a wonderful stay" is een volledig positief commentaar.',
          ru: '"It was a wonderful stay" — полный положительный отзыв.',
          tr: '"It was a wonderful stay" tam bir olumlu geri bildirimdir.',
          ja: '"It was a wonderful stay" は完全なポジティブなフィードバックです。',
        },
      },
    ],
  },
  {
    id: 'interview',
    icon: '💼',
    title: {
      pt: 'Entrevista de Emprego', en: 'Job Interview', de: 'Vorstellungsgespräch', pl: 'Rozmowa kwalifikacyjna',
      es: 'Entrevista de Trabajo', fr: 'Entretien d\'Embauche', it: 'Colloquio di Lavoro', nl: 'Sollicitatiegesprek',
      ru: 'Собеседование', tr: 'İş Görüşmesi', ja: '就職面接',
    },
    description: {
      pt: 'Pratique uma entrevista de emprego em inglês.',
      en: 'Practice a job interview in English.',
      de: 'Übe ein Vorstellungsgespräch auf Englisch.',
      pl: 'Ćwicz rozmowę kwalifikacyjną po angielsku.',
      es: 'Practica una entrevista de trabajo en inglés.',
      fr: 'Pratiquez un entretien d\'embauche en anglais.',
      it: 'Pratica un colloquio di lavoro in inglese.',
      nl: 'Oefen een sollicitatiegesprek in het Engels.',
      ru: 'Практикуйте собеседование на английском.',
      tr: 'İngilizce iş görüşmesi pratik yapın.',
      ja: '英語での就職面接を練習しましょう。',
    },
    difficulty: 'intermediate',
    steps: [
      {
        npc: "Good morning! Please, take a seat. Can you tell me a little about yourself?",
        options: [
          "Of course. I'm a software developer with 5 years of experience.",
          "Me developer five years.",
          "I work the computer long time.",
        ],
        correct: 0,
        explanation: {
          pt: 'Apresente-se com uma frase completa mencionando profissão e experiência.',
          en: 'Introduce yourself with a complete sentence mentioning profession and experience.',
          de: 'Stellen Sie sich mit einem vollständigen Satz vor.',
          pl: 'Przedstaw się pełnym zdaniem z zawodem i doświadczeniem.',
          es: 'Preséntate con una oración completa mencionando profesión y experiencia.',
          fr: 'Présentez-vous avec une phrase complète.',
          it: 'Presentati con una frase completa menzionando professione ed esperienza.',
          nl: 'Stel je voor met een volledige zin.',
          ru: 'Представьтесь полным предложением с профессией и опытом.',
          tr: 'Kendinizi meslek ve deneyimi belirten tam bir cümleyle tanıtın.',
          ja: '職業と経験を含む完全な文で自己紹介しましょう。',
        },
      },
      {
        npc: "Why are you interested in this position?",
        options: [
          "I'm passionate about the company's mission and I believe my skills are a great fit.",
          "I need job money.",
          "Position interest me because work.",
        ],
        correct: 0,
        explanation: {
          pt: 'Mostre entusiasmo e conecte suas habilidades à vaga.',
          en: 'Show enthusiasm and connect your skills to the position.',
          de: 'Zeigen Sie Begeisterung und verbinden Sie Ihre Fähigkeiten mit der Stelle.',
          pl: 'Pokaż entuzjazm i połącz swoje umiejętności ze stanowiskiem.',
          es: 'Muestra entusiasmo y conecta tus habilidades con el puesto.',
          fr: 'Montrez de l\'enthousiasme et reliez vos compétences au poste.',
          it: 'Mostra entusiasmo e collega le tue competenze alla posizione.',
          nl: 'Toon enthousiasme en verbind je vaardigheden met de functie.',
          ru: 'Покажите энтузиазм и свяжите свои навыки с позицией.',
          tr: 'Coşku gösterin ve becerilerinizi pozisyonla ilişkilendirin.',
          ja: '熱意を示し、自分のスキルをポジションに結びつけましょう。',
        },
      },
      {
        npc: "What would you say is your biggest strength?",
        options: [
          "I'm very organized and I work well under pressure.",
          "I strong very much.",
          "Strength is me organized pressure.",
        ],
        correct: 0,
        explanation: {
          pt: '"I\'m very organized" apresenta qualidades de forma profissional.',
          en: '"I\'m very organized" presents qualities professionally.',
          de: '"I\'m very organized" stellt Qualitäten professionell dar.',
          pl: '"I\'m very organized" przedstawia cechy w sposób profesjonalny.',
          es: '"I\'m very organized" presenta cualidades de forma profesional.',
          fr: '"I\'m very organized" présente les qualités de manière professionnelle.',
          it: '"I\'m very organized" presenta le qualità in modo professionale.',
          nl: '"I\'m very organized" presenteert kwaliteiten professioneel.',
          ru: '"I\'m very organized" профессионально представляет качества.',
          tr: '"I\'m very organized" nitelikleri profesyonelce sunar.',
          ja: '"I\'m very organized" はプロフェッショナルに資質を示します。',
        },
      },
      {
        npc: "Where do you see yourself in five years?",
        options: [
          "I'd like to grow into a leadership role within the company.",
          "Five year me boss.",
          "Future leader want be company.",
        ],
        correct: 0,
        explanation: {
          pt: '"I\'d like to grow into..." mostra ambição de forma diplomática.',
          en: '"I\'d like to grow into..." shows ambition diplomatically.',
          de: '"I\'d like to grow into..." zeigt Ehrgeiz auf diplomatische Weise.',
          pl: '"I\'d like to grow into..." dyplomatycznie wyraża ambicje.',
          es: '"I\'d like to grow into..." muestra ambición diplomáticamente.',
          fr: '"I\'d like to grow into..." montre l\'ambition diplomatiquement.',
          it: '"I\'d like to grow into..." mostra ambizione diplomaticamente.',
          nl: '"I\'d like to grow into..." toont ambitie op diplomatieke wijze.',
          ru: '"I\'d like to grow into..." дипломатично показывает амбиции.',
          tr: '"I\'d like to grow into..." hırsı diplomatik bir şekilde gösterir.',
          ja: '"I\'d like to grow into..." は外交的に野心を示します。',
        },
      },
      {
        npc: "Do you have any questions for us?",
        options: [
          "Yes! What does a typical day look like in this role?",
          "No question nothing.",
          "When money start?",
        ],
        correct: 0,
        explanation: {
          pt: 'Sempre faça perguntas na entrevista — isso mostra interesse.',
          en: 'Always ask questions at an interview — it shows interest.',
          de: 'Stellen Sie immer Fragen im Interview — das zeigt Interesse.',
          pl: 'Zawsze zadawaj pytania na rozmowie — to pokazuje zainteresowanie.',
          es: 'Siempre haz preguntas en la entrevista — muestra interés.',
          fr: 'Posez toujours des questions en entretien — cela montre de l\'intérêt.',
          it: 'Fai sempre domande al colloquio — mostra interesse.',
          nl: 'Stel altijd vragen bij een sollicitatie — het toont interesse.',
          ru: 'Всегда задавайте вопросы на собеседовании — это показывает интерес.',
          tr: 'Görüşmede her zaman soru sorun — ilgi gösterir.',
          ja: '面接では必ず質問をしましょう。興味を示すことができます。',
        },
      },
    ],
  },
];

export function getLevel(score, lang = 'en') {
  const levels = {
    pt: ['Iniciante', 'Básico', 'Intermediário', 'Avançado'],
    en: ['Beginner', 'Basic', 'Intermediate', 'Advanced'],
    de: ['Anfänger', 'Grundlagen', 'Mittelstufe', 'Fortgeschritten'],
    pl: ['Początkujący', 'Podstawowy', 'Średnio zaawansowany', 'Zaawansowany'],
    es: ['Principiante', 'Básico', 'Intermedio', 'Avanzado'],
    fr: ['Débutant', 'Basique', 'Intermédiaire', 'Avancé'],
    it: ['Principiante', 'Base', 'Intermedio', 'Avanzato'],
    nl: ['Beginner', 'Basis', 'Gemiddeld', 'Gevorderd'],
    ru: ['Начинающий', 'Базовый', 'Средний', 'Продвинутый'],
    tr: ['Başlangıç', 'Temel', 'Orta', 'İleri'],
    ja: ['初心者', '基礎', '中級', '上級'],
  };
  const names = levels[lang] || levels.en;
  if (score <= 50) return names[0];
  if (score <= 150) return names[1];
  if (score <= 300) return names[2];
  return names[3];
}